# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PyTranscribe',
                'doc_host': 'https://davidweinberg.github.io',
                'git_url': 'https://github.com/davidweinberg/PyTranscribe',
                'lib_path': 'PyTranscribe'},
  'syms': { 'PyTranscribe.core': { 'PyTranscribe.core.JsonToDictation': ('jsontodictation.html#jsontodictation', 'PyTranscribe/core.py'),
                                   'PyTranscribe.core.JsonToDictation.__init__': ( 'jsontodictation.html#jsontodictation.__init__',
                                                                                   'PyTranscribe/core.py'),
                                   'PyTranscribe.core.JsonToDictation.convert': ( 'jsontodictation.html#jsontodictation.convert',
                                                                                  'PyTranscribe/core.py'),
                                   'PyTranscribe.core.JsonToDictation.getSpeakerMap': ( 'jsontodictation.html#jsontodictation.getspeakermap',
                                                                                        'PyTranscribe/core.py'),
                                   'PyTranscribe.core.JsonToDictation.load': ( 'jsontodictation.html#jsontodictation.load',
                                                                               'PyTranscribe/core.py'),
                                   'PyTranscribe.core.JsonToDictation.summary': ( 'jsontodictation.html#jsontodictation.summary',
                                                                                  'PyTranscribe/core.py')}}}
